# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-17 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docinfo',
            name='iscorrect',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='iscomplete',
            field=models.BooleanField(default=False),
        ),
    ]
